---
collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
  - name: geerlingguy.mac

# existiert dort nicht mehr, TODO: cfg aus repo geerling übernehmen
